package com.example.demo.model;

import com.example.demo.enums.Role;
import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

@Entity
// The @Data annotation from Lombok generates getter and setter methods,
// toString, equals, hashCode, and canEqual methods
@Data
// 调用父类的 equals 和 hashCode
@EqualsAndHashCode(callSuper = true)
// modifies the behavior of the setters generated by @Data to return this
// instead of void, enabling method chaining
@Accessors(chain = true)
public class User extends BaseEntity {
	@Column(name = "username", nullable = false, unique = true)
	private String username;

	@Column(name = "password", nullable = false)
	@JsonIgnore
	private String password;

	@Enumerated(EnumType.STRING)
	@Column(name = "role", nullable = false, length = 20)
	private Role role = Role.USER;

	@Column(name = "avatar", nullable = true)
	private String avatar;

	@Column(name = "wechat_open_id", nullable = true, unique = true)
	private String wechatOpenId;
}
